### ISSUE TITLE
Simplify pub sub exercise

### ISSUE THREAD

**Issue by weralabaj** [Particular/Workshop.Microservices#17]
Seems like some elements from exercise 4 (reliable messaging) were left over after changing the exercises order. As a result, the pub sub exercise is very complex, e.g. there are many startup projects, it's not clear why we have reliable and unreliable payment processors (and we don't really have to use both here), seems it'd be sufficient to handle events in just one vertical to show how it works, it's not clear to me why we need two verticals handling the same event (and having the same handler name ;)).

**Comment by dvdstelt** [comment]
There is a class InitiatePaymentProcessCommandHandler that receives the InitiatePaymentProcessCommand message. This could theoretically return "Yep, it worked flawlessly". Instead it calls out to a single project that hosts in a single class both the reliable and unreliable payment provider.

As @SzymonPobiega mentioned, this is used in an advanced exercise. It isn't used in this Module02 though.

In my opinion it services it purpose though:

Instead of returning true there is an actual implementation of something. Makes more sense for end-users looking at this code.
In another module this payment provider is used. Users might miss the connection that it wasn't there in Module02, but it suddenly is in Module03.
It's just a single project that with especially with this StartupProjects PR will be started automatically.

Time catched up with this issue, it's no longer neccesary.
